<?php

namespace Tests\Feature;

use App\Project;
use App\User;
use Faker\Provider\File;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

class ProjectsTest extends TestCase
{
    use WithFaker, RefreshDatabase;

    protected $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = factory(User::class)->create();

        $this->signIn($this->user);
    }

    /** @test */
    function a_user_can_create_project()
    {
        $project = [
            "title" => "title",
            "body" => "body",
        ];

        $projects = Project::all();

        $this->assertCount(1, $projects);
    }
    // css, js, img import

    // css, js, img 확장자 검사
}
